{{- range $r, $repo := .Values.repos }}
  {{- range $c, $chart := $repo.charts }}
    {{- if $chart.enabled }}
      {{ $chartValues := printf "chart-values/%s/%s/%s.yaml" $repo.name $chart.name  $.Values.environment }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ $chart.syncWave | default "10" | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: {{ $chart.name }}
  namespace: {{ $.Values.applicationNamespace }}
spec:
  destination:
    namespace: {{ $chart.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ $repo.url }}
    targetRevision: {{ $chart.version }}
    chart: {{ $chart.name }}
    helm:
      version: "v3"
      values: |-
      {{- $.Files.Get $chartValues | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    {{- end }}
  {{- end }}
{{ end }}
