controller:
  config:
    server-tokens: "false"
  addHeaders:
    X-XSS-Protection: "1; mode=block"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "SAMEORIGIN"
    Referrer-Policy: "strict-origin-when-cross-origin"
  hostNetwork: true
  hostPort:
    enabled: true
  kind: DaemonSet
  publishService:
    enabled: false
  service:
    enabled: false
