name: Merge Branch

on:
  workflow_dispatch:
    inputs:
      source:
      destination:

jobs: 
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show Repo Info
        run: |
          git remote -v
          git branch -va
          
      - name: Merge Branch
        run: |
          git checkout ${{ github.event.inputs.destination }}
          git merge ${{ github.event.inputs.source }}
          git push origin ${{ github.event.inputs.destination }}
