name: Merge Branch

on:
  workflow_dispatch:
    inputs:
      source:
        default: uat
      destination:
        default: main

jobs: 
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: merge branch and push
        run: |
          git checkout ${{ github.event.inputs.destination }}
          git merge origin/${{ github.event.inputs.source }}
          git push origin ${{ github.event.inputs.destination }}
