name: merge branch

on: workflow_dispatch

jobs: 
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show Repo Info
        run: |
          git remote -v
          git branch -va
