name: dispatch

on: 
  repository_dispatch:
    types: [artifacthub]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: show client_payload
        run: |
          echo "name   : ${{ github.event.client_payload.data.package.name }}"
          echo "version: ${{ github.event.client_payload.data.package.version }}"
