name: dispatch

on: 
  repository_dispatch:
    types: [artifacthub]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
      - name: show version
        run: |
          echo "${{ github.event.client_payload.data.package.repository.name }}/${{ github.event.client_payload.data.package.name }}:${{ github.event.client_payload.data.package.version }}"
      - name: yq - update package version
        uses: mikefarah/yq@v4.9.2
        with:
          # The Command which should be run
          cmd: e '.${{ github.event.client_payload.data.package.repository.name }}.${{ github.event.client_payload.data.package.name }} = "${{ github.event.client_payload.data.package.version }}"' -i current-chart-versions.yaml
      - name: commit and push
        run: |
          # Stage the file, commit and push
          git add current-chart-versions.yaml
          git commit -m "update version of ${{ github.event.client_payload.data.package.repository.name }}.${{ github.event.client_payload.data.package.name }} to ${{ github.event.client_payload.data.package.version }}"
          git push origin main
