name: test gh

on:
  workflow_dispatch:

jobs:
  test-gh:
    runs-on: ubuntu-latest
    steps:
      - name: get repo url
        id: repo-url
        uses: fjogeleit/http-request-action@master
        with:
          method: GET
          url: "https://artifacthub.io/api/v1/repositories/search?offset=0&limit=20&kind=0&user=300481&org=300481&name=testrepo"
      - name: echo output
        run: |
          echo test 1 ${{ steps.repo-url.outputs.response }}
          echo test 2 ${{ fromJSON(steps.repo-url.outputs.response)[0].url }}
          echo test 3 ${{ fromJSON(steps.repo-url.outputs.response).*.url }}
          echo test 4 ${{ fromJSON(steps.repo-url.outputs.response) }}
