name: test tojson

on:
  workflow_dispatch:

jobs:
  test-tojson:
    runs-on: ubuntu-latest
    steps:
      - name: echo output
        env:
          JSON: ${{ toJSON(github) }}
        run: |
          echo "${JSON}"
