name: Update YAML

on:
  workflow_dispatch:
    inputs:
      propertyPath:
        description: 'propertyPath'
        required: true
        default: 'foo'
      value:
        description: 'value'
        required: true
        default: 'bar'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-yaml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Update my-test.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'my-test.yaml'
          propertyPath: '${{ github.event.inputs.propertyPath }}'
          value: ${{ github.event.inputs.value }}
          commitChange: false
          updateFile: true
      - name: Commit and push
        run: |
          git config --global user.name '300481'
          git config --global user.email '300481@users.noreply.github.com'
          git commit -am "add ${{ github.event.inputs.value }} to ${{ github.event.inputs.propertyPath }}"
          git push
