name: update chart versions

on: 
  repository_dispatch:
    types: [artifacthub]

jobs:
  update_chart_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: update chart
        run: |
          ./scripts/update-chart-versions.sh "{{ toJSON(github.event.client_payload) }}"
          ./scripts/generate-helm-manifests.sh
      - name: commit and push
        run: |
          git add helm-charts.yaml chart-manifests
          git commit -m "update version of ${{ github.event.client_payload.data.package.repository.name }}/${{ github.event.client_payload.data.package.name }} to ${{ github.event.client_payload.data.package.version }}"
          git push origin main
